name: "Godot Export"
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

jobs:
  export:
    name: Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
          cp -r /root/.local/share/godot/export_templates/4.2.2.stable/* ~/.local/share/godot/export_templates/4.2.2.stable/

      - name: Export project
        run: |
          mkdir -p build/windows
          mkdir -p build/linux
          
          godot --headless --export-release "Windows Desktop" build/windows/WonkyLands.exe
          godot --headless --export-release "Linux/X11" build/linux/WonkyLands.x86_64
          
          chmod +x build/linux/WonkyLands.x86_64

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/WonkyLands.exe

      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/WonkyLands.x86_64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/windows/WonkyLands.exe
            build/linux/WonkyLands.x86_64